- name: Configure dev user
  hosts: update_hosts
  become: true
  become_method: sudo
  
  vars_files:
    - "../../global_vars/users.yaml"
    - "../../global_vars/passwords.yaml"
  vars:
    users:
      - "dev"

  roles:
    - role: "../roles/config_user"

- name: Ensuring base packages are install_listed
  hosts: update_hosts
  become: true
  become_method: sudo

  vars:
    listed_packages:
      - epel-release
      - podman
      - vim
      - curl
      - wget
      - git
      - telnet
      - bind-utils
      - tree
      - chrony
      - zip
      - unzip
      - ipa-client
  
  roles:
    - role: "../roles/install_listed"

